# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import fermyon_spin_http_types
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


def send_request(req: fermyon_spin_http_types.Request) -> fermyon_spin_http_types.Response:
    """
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_http_types.HttpError)`
    """
    raise NotImplementedError
