# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


@dataclass
class Error_Provider:
    value: str


@dataclass
class Error_InvalidKey:
    value: str


@dataclass
class Error_InvalidSchema:
    value: str


@dataclass
class Error_Other:
    value: str


Error = Union[Error_Provider, Error_InvalidKey, Error_InvalidSchema, Error_Other]



def get_config(key: str) -> str:
    """
    Get a configuration value for the current component.
    The config key must match one defined in in the component manifest.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_config.Error)`
    """
    raise NotImplementedError
