# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import fermyon_spin_redis_types
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


def publish(address: str, channel: str, payload: bytes) -> None:
    """
    Publish a Redis message to the specificed channel and return an error, if any.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_redis_types.Error)`
    """
    raise NotImplementedError
def get(address: str, key: str) -> bytes:
    """
    Get the value of a key.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_redis_types.Error)`
    """
    raise NotImplementedError
def set(address: str, key: str, value: bytes) -> None:
    """
    Set key to value. If key alreads holds a value, it is overwritten.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_redis_types.Error)`
    """
    raise NotImplementedError
def incr(address: str, key: str) -> int:
    """
    Increments the number stored at key by one. If the key does not exist, it is set to 0 before performing the operation.
    An error is returned if the key contains a value of the wrong type or contains a string that can not be represented as integer.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_redis_types.Error)`
    """
    raise NotImplementedError
def del_(address: str, keys: List[str]) -> int:
    """
    Removes the specified keys. A key is ignored if it does not exist.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_redis_types.Error)`
    """
    raise NotImplementedError
def sadd(address: str, key: str, values: List[str]) -> int:
    """
    Add the specified `values` to the set named `key`, returning the number of newly-added values.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_redis_types.Error)`
    """
    raise NotImplementedError
def smembers(address: str, key: str) -> List[str]:
    """
    Retrieve the contents of the set named `key`.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_redis_types.Error)`
    """
    raise NotImplementedError
def srem(address: str, key: str, values: List[str]) -> int:
    """
    Remove the specified `values` from the set named `key`, returning the number of newly-removed values.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_redis_types.Error)`
    """
    raise NotImplementedError
def execute(address: str, command: str, arguments: List[fermyon_spin_redis_types.RedisParameter]) -> List[fermyon_spin_redis_types.RedisResult]:
    """
    Execute an arbitrary Redis command and receive the result.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_redis_types.Error)`
    """
    raise NotImplementedError
