# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter

class Method(Enum):
    GET = 0
    POST = 1
    PUT = 2
    DELETE = 3
    PATCH = 4
    HEAD = 5
    OPTIONS = 6

@dataclass
class Request:
    method: Method
    uri: str
    headers: List[Tuple[str, str]]
    params: List[Tuple[str, str]]
    body: Optional[bytes]

@dataclass
class Response:
    status: int
    headers: Optional[List[Tuple[str, str]]]
    body: Optional[bytes]

class HttpError(Enum):
    SUCCESS = 0
    DESTINATION_NOT_ALLOWED = 1
    INVALID_URL = 2
    REQUEST_ERROR = 3
    RUNTIME_ERROR = 4
    TOO_MANY_REQUESTS = 5


