# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


@dataclass
class Error_StoreTableFull:
    pass


@dataclass
class Error_NoSuchStore:
    pass


@dataclass
class Error_AccessDenied:
    pass


@dataclass
class Error_InvalidStore:
    pass


@dataclass
class Error_NoSuchKey:
    pass


@dataclass
class Error_Io:
    value: str


Error = Union[Error_StoreTableFull, Error_NoSuchStore, Error_AccessDenied, Error_InvalidStore, Error_NoSuchKey, Error_Io]
"""
The set of errors which may be raised by functions in this interface
"""



def open(name: str) -> int:
    """
    Open the store with the specified name.
    
    If `name` is "default", the default store is opened.  Otherwise,
    `name` must refer to a store defined and configured in a runtime
    configuration file supplied with the application.
    
    `error::no-such-store` will be raised if the `name` is not recognized.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_key_value.Error)`
    """
    raise NotImplementedError
def get(store: int, key: str) -> bytes:
    """
    Get the value associated with the specified `key` from the specified
    `store`.
    
    `error::invalid-store` will be raised if `store` is not a valid handle
    to an open store, and `error::no-such-key` will be raised if there is no
    tuple for `key` in `store`.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_key_value.Error)`
    """
    raise NotImplementedError
def set(store: int, key: str, value: bytes) -> None:
    """
    Set the `value` associated with the specified `key` in the specified
    `store`, overwriting any existing value.
    
    `error::invalid-store` will be raised if `store` is not a valid handle
    to an open store.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_key_value.Error)`
    """
    raise NotImplementedError
def delete(store: int, key: str) -> None:
    """
    Delete the tuple with the specified `key` from the specified `store`.
    
    `error::invalid-store` will be raised if `store` is not a valid handle
    to an open store.  No error is raised if a tuple did not previously
    exist for `key`.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_key_value.Error)`
    """
    raise NotImplementedError
def exists(store: int, key: str) -> bool:
    """
    Return whether a tuple exists for the specified `key` in the specified
    `store`.
    
    `error::invalid-store` will be raised if `store` is not a valid handle
    to an open store.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_key_value.Error)`
    """
    raise NotImplementedError
def get_keys(store: int) -> List[str]:
    """
    Return a list of all the keys in the specified `store`.
    
    `error::invalid-store` will be raised if `store` is not a valid handle
    to an open store.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_key_value.Error)`
    """
    raise NotImplementedError
def close(store: int) -> None:
    """
    Close the specified `store`.
    
    This has no effect if `store` is not a valid handle to an open store.
    """
    raise NotImplementedError
