# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import fermyon_spin_rdbms_types_2_0_0
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter

class Connection:
    """
    A connection to a MySQL database.
    """
    
    @classmethod
    def open(cls, address: str) -> Self:
        """
        Open a connection to the MySQL instance at `address`.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_rdbms_types_2_0_0.Error)`
        """
        raise NotImplementedError
    def query(self, statement: str, params: List[fermyon_spin_rdbms_types_2_0_0.ParameterValue]) -> fermyon_spin_rdbms_types_2_0_0.RowSet:
        """
        query the database: select
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_rdbms_types_2_0_0.Error)`
        """
        raise NotImplementedError
    def execute(self, statement: str, params: List[fermyon_spin_rdbms_types_2_0_0.ParameterValue]) -> None:
        """
        execute command to the database: insert, update, delete
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_rdbms_types_2_0_0.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



