# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import fermyon_spin_rdbms_types
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


@dataclass
class MysqlError_Success:
    pass


@dataclass
class MysqlError_ConnectionFailed:
    value: str


@dataclass
class MysqlError_BadParameter:
    value: str


@dataclass
class MysqlError_QueryFailed:
    value: str


@dataclass
class MysqlError_ValueConversionFailed:
    value: str


@dataclass
class MysqlError_OtherError:
    value: str


MysqlError = Union[MysqlError_Success, MysqlError_ConnectionFailed, MysqlError_BadParameter, MysqlError_QueryFailed, MysqlError_ValueConversionFailed, MysqlError_OtherError]
"""
General purpose error.
"""



def query(address: str, statement: str, params: List[fermyon_spin_rdbms_types.ParameterValue]) -> fermyon_spin_rdbms_types.RowSet:
    """
    query the database: select
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_mysql.MysqlError)`
    """
    raise NotImplementedError
def execute(address: str, statement: str, params: List[fermyon_spin_rdbms_types.ParameterValue]) -> None:
    """
    execute command to the database: insert, update, delete
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.fermyon_spin_mysql.MysqlError)`
    """
    raise NotImplementedError
