# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


@dataclass
class Error_StoreTableFull:
    pass


@dataclass
class Error_NoSuchStore:
    pass


@dataclass
class Error_AccessDenied:
    pass


@dataclass
class Error_Other:
    value: str


Error = Union[Error_StoreTableFull, Error_NoSuchStore, Error_AccessDenied, Error_Other]
"""
The set of errors which may be raised by functions in this interface
"""


class Store:
    """
    An open key-value store
    """
    
    @classmethod
    async def open(cls, label: str) -> Self:
        """
        Open the store with the specified label.
        
        `label` must refer to a store allowed in the spin.toml manifest.
        
        `error::no-such-store` will be raised if the `label` is not recognized.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.spin_key_value_key_value_3_0_0.Error)`
        """
        raise NotImplementedError
    async def get(self, key: str) -> Optional[bytes]:
        """
        Get the value associated with the specified `key`
        
        Returns `ok(none)` if the key does not exist.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.spin_key_value_key_value_3_0_0.Error)`
        """
        raise NotImplementedError
    async def set(self, key: str, value: bytes) -> None:
        """
        Set the `value` associated with the specified `key` overwriting any existing value.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.spin_key_value_key_value_3_0_0.Error)`
        """
        raise NotImplementedError
    async def delete(self, key: str) -> None:
        """
        Delete the tuple with the specified `key`
        
        No error is raised if a tuple did not previously exist for `key`.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.spin_key_value_key_value_3_0_0.Error)`
        """
        raise NotImplementedError
    async def exists(self, key: str) -> bool:
        """
        Return whether a tuple exists for the specified `key`
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.spin_key_value_key_value_3_0_0.Error)`
        """
        raise NotImplementedError
    async def get_keys(self) -> Tuple[StreamReader[str], FutureReader[Result[None, Error]]]:
        """
        Return a list of all the keys
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



