# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
An interface providing an optional `terminal-output` for stderr as a
link-time authority.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import wasi_cli_terminal_output_0_3_0_rc_2026_03_15
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


def get_terminal_stderr() -> Optional[wasi_cli_terminal_output_0_3_0_rc_2026_03_15.TerminalOutput]:
    """
    If stderr is connected to a terminal, return a `terminal-output` handle
    allowing further interaction with it.
    """
    raise NotImplementedError
