# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
This interface defines an HTTP client for sending "outgoing" requests.

Most components are expected to import this interface to provide the
capability to send HTTP requests to arbitrary destinations on a network.

The type signature of `client.send` is the same as `handler.handle`. This
duplication is currently necessary because some Component Model tooling
(including WIT itself) is unable to represent a component importing two
instances of the same interface. A `client.send` import may be linked
directly to a `handler.handle` export to bypass the network.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import wasi_http_types_0_3_0_rc_2026_03_15
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


async def send(request: wasi_http_types_0_3_0_rc_2026_03_15.Request) -> wasi_http_types_0_3_0_rc_2026_03_15.Response:
    """
    This function may be used to either send an outgoing request over the
    network or to forward it to another component.
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_http_types_0_3_0_rc_2026_03_15.ErrorCode)`
    """
    raise NotImplementedError
