# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
WASI Monotonic Clock is a clock API intended to let users measure elapsed
time.

It is intended to be portable at least between Unix-family platforms and
Windows.

A monotonic clock is a clock which has an unspecified initial value, and
successive reads of the clock will produce non-decreasing values.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


def now() -> int:
    """
    Read the current value of the clock.
    
    The clock is monotonic, therefore calling this function repeatedly will
    produce a sequence of non-decreasing values.
    
    For completeness, this function traps if it's not possible to represent
    the value of the clock in a `mark`. Consequently, implementations
    should ensure that the starting time is low enough to avoid the
    possibility of overflow in practice.
    """
    raise NotImplementedError
def get_resolution() -> int:
    """
    Query the resolution of the clock. Returns the duration of time
    corresponding to a clock tick.
    """
    raise NotImplementedError
async def wait_until(when: int) -> None:
    """
    Wait until the specified mark has occurred.
    """
    raise NotImplementedError
async def wait_for(how_long: int) -> None:
    """
    Wait for the specified duration to elapse.
    """
    raise NotImplementedError
