# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import wasi_sockets_types_0_3_0_rc_2026_03_15
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


@dataclass
class ErrorCode_AccessDenied:
    pass


@dataclass
class ErrorCode_InvalidArgument:
    pass


@dataclass
class ErrorCode_NameUnresolvable:
    pass


@dataclass
class ErrorCode_TemporaryResolverFailure:
    pass


@dataclass
class ErrorCode_PermanentResolverFailure:
    pass


@dataclass
class ErrorCode_Other:
    value: Optional[str]


ErrorCode = Union[ErrorCode_AccessDenied, ErrorCode_InvalidArgument, ErrorCode_NameUnresolvable, ErrorCode_TemporaryResolverFailure, ErrorCode_PermanentResolverFailure, ErrorCode_Other]
"""
Lookup error codes.
"""



async def resolve_addresses(name: str) -> List[wasi_sockets_types_0_3_0_rc_2026_03_15.IpAddress]:
    """
    Resolve an internet host name to a list of IP addresses.
    
    Unicode domain names are automatically converted to ASCII using IDNA
    encoding. If the input is an IP address string, the address is parsed
    and returned as-is without making any external requests.
    
    See the wasi-socket proposal README.md for a comparison with getaddrinfo.
    
    The results are returned in connection order preference.
    
    This function never succeeds with 0 results. It either fails or succeeds
    with at least one address. Additionally, this function never returns
    IPv4-mapped IPv6 addresses.
    
    # References:
    - <https://pubs.opengroup.org/onlinepubs/9699919799/functions/getaddrinfo.html>
    - <https://man7.org/linux/man-pages/man3/getaddrinfo.3.html>
    - <https://learn.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo>
    - <https://man.freebsd.org/cgi/man.cgi?query=getaddrinfo&sektion=3>
    
    Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_sockets_ip_name_lookup_0_3_0_rc_2026_03_15.ErrorCode)`
    """
    raise NotImplementedError
