# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


def exit(status: Result[None, None]) -> None:
    """
    Exit the current instance and any linked instances.
    """
    raise NotImplementedError
def exit_with_code(status_code: int) -> None:
    """
    Exit the current instance and any linked instances, reporting the
    specified status code to the host.
    
    The meaning of the code depends on the context, with 0 usually meaning
    "success", and other values indicating various types of failure.
    
    This function does not return; the effect is analogous to a trap, but
    without the connotation that something bad has happened.
    """
    raise NotImplementedError
