# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
WASI filesystem is a filesystem API primarily intended to let users run WASI
programs that access their files on their existing filesystems, without
significant overhead.

Paths are passed as interface-type `string`s, meaning they must consist of
a sequence of Unicode Scalar Values (USVs). Some filesystems may contain
paths which are not accessible by this API.

The directory separator in WASI is always the forward-slash (`/`).

All paths in WASI are relative paths, and are interpreted relative to a
`descriptor` referring to a base directory. If a `path` argument to any WASI
function starts with `/`, or if any step of resolving a `path`, including
`..` and symbolic link steps, reaches a directory outside of the base
directory, or reaches a symlink to an absolute or rooted path in the
underlying filesystem, the function fails with `error-code::not-permitted`.

For more information about WASI path resolution and sandboxing, see
[WASI filesystem path resolution].

Though this package presents a portable interface modelled on POSIX, it
prioritizes compatibility over portability: allowing users to access their
files on their machine is more important than exposing a single semantics
across all platforms.  Notably, depending on the underlying operating system
and file system:
  * Paths may be case-folded or not.
  * Deleting (unlinking) a file may fail if there are other file descriptors
    open.
  * Durability and atomicity of changes to underlying files when there are
    concurrent writers.

Users that need well-defined, portable semantics should use a key-value
store or a database instead.

[WASI filesystem path resolution]: https://github.com/WebAssembly/wasi-filesystem/blob/main/path-resolution.md
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import wasi_clocks_system_clock_0_3_0_rc_2026_03_15
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


@dataclass
class DescriptorType_BlockDevice:
    pass


@dataclass
class DescriptorType_CharacterDevice:
    pass


@dataclass
class DescriptorType_Directory:
    pass


@dataclass
class DescriptorType_Fifo:
    pass


@dataclass
class DescriptorType_SymbolicLink:
    pass


@dataclass
class DescriptorType_RegularFile:
    pass


@dataclass
class DescriptorType_Socket:
    pass


@dataclass
class DescriptorType_Other:
    value: Optional[str]


DescriptorType = Union[DescriptorType_BlockDevice, DescriptorType_CharacterDevice, DescriptorType_Directory, DescriptorType_Fifo, DescriptorType_SymbolicLink, DescriptorType_RegularFile, DescriptorType_Socket, DescriptorType_Other]
"""
The type of a filesystem object referenced by a descriptor.

Note: This was called `filetype` in earlier versions of WASI.
"""


class DescriptorFlags(Flag):
    """
    Descriptor flags.
    
    Note: This was called `fdflags` in earlier versions of WASI.
    """
    READ = auto()
    WRITE = auto()
    FILE_INTEGRITY_SYNC = auto()
    DATA_INTEGRITY_SYNC = auto()
    REQUESTED_WRITE_SYNC = auto()
    MUTATE_DIRECTORY = auto()

class PathFlags(Flag):
    """
    Flags determining the method of how paths are resolved.
    """
    SYMLINK_FOLLOW = auto()

class OpenFlags(Flag):
    """
    Open flags used by `open-at`.
    """
    CREATE = auto()
    DIRECTORY = auto()
    EXCLUSIVE = auto()
    TRUNCATE = auto()

@dataclass
class DescriptorStat:
    """
    File attributes.
    
    Note: This was called `filestat` in earlier versions of WASI.
    """
    type: DescriptorType
    link_count: int
    size: int
    data_access_timestamp: Optional[wasi_clocks_system_clock_0_3_0_rc_2026_03_15.Instant]
    data_modification_timestamp: Optional[wasi_clocks_system_clock_0_3_0_rc_2026_03_15.Instant]
    status_change_timestamp: Optional[wasi_clocks_system_clock_0_3_0_rc_2026_03_15.Instant]


@dataclass
class NewTimestamp_NoChange:
    pass


@dataclass
class NewTimestamp_Now:
    pass


@dataclass
class NewTimestamp_Timestamp:
    value: wasi_clocks_system_clock_0_3_0_rc_2026_03_15.Instant


NewTimestamp = Union[NewTimestamp_NoChange, NewTimestamp_Now, NewTimestamp_Timestamp]
"""
When setting a timestamp, this gives the value to set it to.
"""


@dataclass
class DirectoryEntry:
    """
    A directory entry.
    """
    type: DescriptorType
    name: str


@dataclass
class ErrorCode_Access:
    pass


@dataclass
class ErrorCode_Already:
    pass


@dataclass
class ErrorCode_BadDescriptor:
    pass


@dataclass
class ErrorCode_Busy:
    pass


@dataclass
class ErrorCode_Deadlock:
    pass


@dataclass
class ErrorCode_Quota:
    pass


@dataclass
class ErrorCode_Exist:
    pass


@dataclass
class ErrorCode_FileTooLarge:
    pass


@dataclass
class ErrorCode_IllegalByteSequence:
    pass


@dataclass
class ErrorCode_InProgress:
    pass


@dataclass
class ErrorCode_Interrupted:
    pass


@dataclass
class ErrorCode_Invalid:
    pass


@dataclass
class ErrorCode_Io:
    pass


@dataclass
class ErrorCode_IsDirectory:
    pass


@dataclass
class ErrorCode_Loop:
    pass


@dataclass
class ErrorCode_TooManyLinks:
    pass


@dataclass
class ErrorCode_MessageSize:
    pass


@dataclass
class ErrorCode_NameTooLong:
    pass


@dataclass
class ErrorCode_NoDevice:
    pass


@dataclass
class ErrorCode_NoEntry:
    pass


@dataclass
class ErrorCode_NoLock:
    pass


@dataclass
class ErrorCode_InsufficientMemory:
    pass


@dataclass
class ErrorCode_InsufficientSpace:
    pass


@dataclass
class ErrorCode_NotDirectory:
    pass


@dataclass
class ErrorCode_NotEmpty:
    pass


@dataclass
class ErrorCode_NotRecoverable:
    pass


@dataclass
class ErrorCode_Unsupported:
    pass


@dataclass
class ErrorCode_NoTty:
    pass


@dataclass
class ErrorCode_NoSuchDevice:
    pass


@dataclass
class ErrorCode_Overflow:
    pass


@dataclass
class ErrorCode_NotPermitted:
    pass


@dataclass
class ErrorCode_Pipe:
    pass


@dataclass
class ErrorCode_ReadOnly:
    pass


@dataclass
class ErrorCode_InvalidSeek:
    pass


@dataclass
class ErrorCode_TextFileBusy:
    pass


@dataclass
class ErrorCode_CrossDevice:
    pass


@dataclass
class ErrorCode_Other:
    value: Optional[str]


ErrorCode = Union[ErrorCode_Access, ErrorCode_Already, ErrorCode_BadDescriptor, ErrorCode_Busy, ErrorCode_Deadlock, ErrorCode_Quota, ErrorCode_Exist, ErrorCode_FileTooLarge, ErrorCode_IllegalByteSequence, ErrorCode_InProgress, ErrorCode_Interrupted, ErrorCode_Invalid, ErrorCode_Io, ErrorCode_IsDirectory, ErrorCode_Loop, ErrorCode_TooManyLinks, ErrorCode_MessageSize, ErrorCode_NameTooLong, ErrorCode_NoDevice, ErrorCode_NoEntry, ErrorCode_NoLock, ErrorCode_InsufficientMemory, ErrorCode_InsufficientSpace, ErrorCode_NotDirectory, ErrorCode_NotEmpty, ErrorCode_NotRecoverable, ErrorCode_Unsupported, ErrorCode_NoTty, ErrorCode_NoSuchDevice, ErrorCode_Overflow, ErrorCode_NotPermitted, ErrorCode_Pipe, ErrorCode_ReadOnly, ErrorCode_InvalidSeek, ErrorCode_TextFileBusy, ErrorCode_CrossDevice, ErrorCode_Other]
"""
Error codes returned by functions, similar to `errno` in POSIX.
Not all of these error codes are returned by the functions provided by this
API; some are used in higher-level library layers, and others are provided
merely for alignment with POSIX.
"""


class Advice(Enum):
    """
    File or memory access pattern advisory information.
    """
    NORMAL = 0
    SEQUENTIAL = 1
    RANDOM = 2
    WILL_NEED = 3
    DONT_NEED = 4
    NO_REUSE = 5

@dataclass
class MetadataHashValue:
    """
    A 128-bit hash value, split into parts because wasm doesn't have a
    128-bit integer type.
    """
    lower: int
    upper: int

class Descriptor:
    """
    A descriptor is a reference to a filesystem object, which may be a file,
    directory, named pipe, special file, or other object on which filesystem
    calls may be made.
    """
    
    def read_via_stream(self, offset: int) -> Tuple[ByteStreamReader, FutureReader[Result[None, ErrorCode]]]:
        """
        Return a stream for reading from a file.
        
        Multiple read, write, and append streams may be active on the same open
        file and they do not interfere with each other.
        
        This function returns a `stream` which provides the data received from the
        file, and a `future` providing additional error information in case an
        error is encountered.
        
        If no error is encountered, `stream.read` on the `stream` will return
        `read-status::closed` with no `error-context` and the future resolves to
        the value `ok`. If an error is encountered, `stream.read` on the
        `stream` returns `read-status::closed` with an `error-context` and the future
        resolves to `err` with an `error-code`.
        
        Note: This is similar to `pread` in POSIX.
        """
        raise NotImplementedError
    def write_via_stream(self, data: ByteStreamReader, offset: int) -> FutureReader[Result[None, ErrorCode]]:
        """
        Return a stream for writing to a file, if available.
        
        May fail with an error-code describing why the file cannot be written.
        
        It is valid to write past the end of a file; the file is extended to the
        extent of the write, with bytes between the previous end and the start of
        the write set to zero.
        
        This function returns once either full contents of the stream are
        written or an error is encountered.
        
        Note: This is similar to `pwrite` in POSIX.
        """
        raise NotImplementedError
    def append_via_stream(self, data: ByteStreamReader) -> FutureReader[Result[None, ErrorCode]]:
        """
        Return a stream for appending to a file, if available.
        
        May fail with an error-code describing why the file cannot be appended.
        
        This function returns once either full contents of the stream are
        written or an error is encountered.
        
        Note: This is similar to `write` with `O_APPEND` in POSIX.
        """
        raise NotImplementedError
    async def advise(self, offset: int, length: int, advice: Advice) -> None:
        """
        Provide file advisory information on a descriptor.
        
        This is similar to `posix_fadvise` in POSIX.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def sync_data(self) -> None:
        """
        Synchronize the data of a file to disk.
        
        This function succeeds with no effect if the file descriptor is not
        opened for writing.
        
        Note: This is similar to `fdatasync` in POSIX.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def get_flags(self) -> DescriptorFlags:
        """
        Get flags associated with a descriptor.
        
        Note: This returns similar flags to `fcntl(fd, F_GETFL)` in POSIX.
        
        Note: This returns the value that was the `fs_flags` value returned
        from `fdstat_get` in earlier versions of WASI.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def get_type(self) -> DescriptorType:
        """
        Get the dynamic type of a descriptor.
        
        Note: This returns the same value as the `type` field of the `fd-stat`
        returned by `stat`, `stat-at` and similar.
        
        Note: This returns similar flags to the `st_mode & S_IFMT` value provided
        by `fstat` in POSIX.
        
        Note: This returns the value that was the `fs_filetype` value returned
        from `fdstat_get` in earlier versions of WASI.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def set_size(self, size: int) -> None:
        """
        Adjust the size of an open file. If this increases the file's size, the
        extra bytes are filled with zeros.
        
        Note: This was called `fd_filestat_set_size` in earlier versions of WASI.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def set_times(self, data_access_timestamp: NewTimestamp, data_modification_timestamp: NewTimestamp) -> None:
        """
        Adjust the timestamps of an open file or directory.
        
        Note: This is similar to `futimens` in POSIX.
        
        Note: This was called `fd_filestat_set_times` in earlier versions of WASI.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    def read_directory(self) -> Tuple[StreamReader[DirectoryEntry], FutureReader[Result[None, ErrorCode]]]:
        """
        Read directory entries from a directory.
        
        On filesystems where directories contain entries referring to themselves
        and their parents, often named `.` and `..` respectively, these entries
        are omitted.
        
        This always returns a new stream which starts at the beginning of the
        directory. Multiple streams may be active on the same directory, and they
        do not interfere with each other.
        
        This function returns a future, which will resolve to an error code if
        reading full contents of the directory fails.
        """
        raise NotImplementedError
    async def sync(self) -> None:
        """
        Synchronize the data and metadata of a file to disk.
        
        This function succeeds with no effect if the file descriptor is not
        opened for writing.
        
        Note: This is similar to `fsync` in POSIX.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def create_directory_at(self, path: str) -> None:
        """
        Create a directory.
        
        Note: This is similar to `mkdirat` in POSIX.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def stat(self) -> DescriptorStat:
        """
        Return the attributes of an open file or directory.
        
        Note: This is similar to `fstat` in POSIX, except that it does not return
        device and inode information. For testing whether two descriptors refer to
        the same underlying filesystem object, use `is-same-object`. To obtain
        additional data that can be used do determine whether a file has been
        modified, use `metadata-hash`.
        
        Note: This was called `fd_filestat_get` in earlier versions of WASI.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def stat_at(self, path_flags: PathFlags, path: str) -> DescriptorStat:
        """
        Return the attributes of a file or directory.
        
        Note: This is similar to `fstatat` in POSIX, except that it does not
        return device and inode information. See the `stat` description for a
        discussion of alternatives.
        
        Note: This was called `path_filestat_get` in earlier versions of WASI.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def set_times_at(self, path_flags: PathFlags, path: str, data_access_timestamp: NewTimestamp, data_modification_timestamp: NewTimestamp) -> None:
        """
        Adjust the timestamps of a file or directory.
        
        Note: This is similar to `utimensat` in POSIX.
        
        Note: This was called `path_filestat_set_times` in earlier versions of
        WASI.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def link_at(self, old_path_flags: PathFlags, old_path: str, new_descriptor: Self, new_path: str) -> None:
        """
        Create a hard link.
        
        Fails with `error-code::no-entry` if the old path does not exist,
        with `error-code::exist` if the new path already exists, and
        `error-code::not-permitted` if the old path is not a file.
        
        Note: This is similar to `linkat` in POSIX.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def open_at(self, path_flags: PathFlags, path: str, open_flags: OpenFlags, flags: DescriptorFlags) -> Self:
        """
        Open a file or directory.
        
        If `flags` contains `descriptor-flags::mutate-directory`, and the base
        descriptor doesn't have `descriptor-flags::mutate-directory` set,
        `open-at` fails with `error-code::read-only`.
        
        If `flags` contains `write` or `mutate-directory`, or `open-flags`
        contains `truncate` or `create`, and the base descriptor doesn't have
        `descriptor-flags::mutate-directory` set, `open-at` fails with
        `error-code::read-only`.
        
        Note: This is similar to `openat` in POSIX.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def readlink_at(self, path: str) -> str:
        """
        Read the contents of a symbolic link.
        
        If the contents contain an absolute or rooted path in the underlying
        filesystem, this function fails with `error-code::not-permitted`.
        
        Note: This is similar to `readlinkat` in POSIX.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def remove_directory_at(self, path: str) -> None:
        """
        Remove a directory.
        
        Return `error-code::not-empty` if the directory is not empty.
        
        Note: This is similar to `unlinkat(fd, path, AT_REMOVEDIR)` in POSIX.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def rename_at(self, old_path: str, new_descriptor: Self, new_path: str) -> None:
        """
        Rename a filesystem object.
        
        Note: This is similar to `renameat` in POSIX.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def symlink_at(self, old_path: str, new_path: str) -> None:
        """
        Create a symbolic link (also known as a "symlink").
        
        If `old-path` starts with `/`, the function fails with
        `error-code::not-permitted`.
        
        Note: This is similar to `symlinkat` in POSIX.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def unlink_file_at(self, path: str) -> None:
        """
        Unlink a filesystem object that is not a directory.
        
        This is similar to `unlinkat(fd, path, 0)` in POSIX.
        
        Error returns are as specified by POSIX.
        
        If the filesystem object is a directory, `error-code::access` or
        `error-code::is-directory` may be returned instead of the
        POSIX-specified `error-code::not-permitted`.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def is_same_object(self, other: Self) -> bool:
        """
        Test whether two descriptors refer to the same filesystem object.
        
        In POSIX, this corresponds to testing whether the two descriptors have the
        same device (`st_dev`) and inode (`st_ino` or `d_ino`) numbers.
        wasi-filesystem does not expose device and inode numbers, so this function
        may be used instead.
        """
        raise NotImplementedError
    async def metadata_hash(self) -> MetadataHashValue:
        """
        Return a hash of the metadata associated with a filesystem object referred
        to by a descriptor.
        
        This returns a hash of the last-modification timestamp and file size, and
        may also include the inode number, device number, birth timestamp, and
        other metadata fields that may change when the file is modified or
        replaced. It may also include a secret value chosen by the
        implementation and not otherwise exposed.
        
        Implementations are encouraged to provide the following properties:
        
         - If the file is not modified or replaced, the computed hash value should
           usually not change.
         - If the object is modified or replaced, the computed hash value should
           usually change.
         - The inputs to the hash should not be easily computable from the
           computed hash.
        
        However, none of these is required.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    async def metadata_hash_at(self, path_flags: PathFlags, path: str) -> MetadataHashValue:
        """
        Return a hash of the metadata associated with a filesystem object referred
        to by a directory descriptor and a relative path.
        
        This performs the same hash computation as `metadata-hash`.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



