# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
The insecure interface for insecure pseudo-random numbers.

It is intended to be portable at least between Unix-family platforms and
Windows.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


def get_insecure_random_bytes(max_len: int) -> bytes:
    """
    Return up to `max-len` insecure pseudo-random bytes.
    
    This function is not cryptographically secure. Do not use it for
    anything related to security.
    
    There are no requirements on the values of the returned bytes, however
    implementations are encouraged to return evenly distributed values with
    a long period.
    
    Implementations MAY return fewer bytes than requested (a short read).
    Callers that require exactly `max-len` bytes MUST call this function in
    a loop until the desired number of bytes has been accumulated.
    Implementations MUST return at least 1 byte when `max-len` is greater
    than zero. When `max-len` is zero, implementations MUST return an empty
    list without trapping.
    """
    raise NotImplementedError
def get_insecure_random_u64() -> int:
    """
    Return an insecure pseudo-random `u64` value.
    
    This function returns the same type of pseudo-random data as
    `get-insecure-random-bytes`, represented as a `u64`.
    """
    raise NotImplementedError
