# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
An interface providing an optional `terminal-input` for stdin as a
link-time authority.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import wasi_cli_terminal_input_0_2_0
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


def get_terminal_stdin() -> Optional[wasi_cli_terminal_input_0_2_0.TerminalInput]:
    """
    If stdin is connected to a terminal, return a `terminal-input` handle
    allowing further interaction with it.
    """
    raise NotImplementedError
