# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
This interface defines all of the types and methods for implementing HTTP
Requests and Responses, as well as their headers, trailers, and bodies.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


@dataclass
class Method_Get:
    pass


@dataclass
class Method_Head:
    pass


@dataclass
class Method_Post:
    pass


@dataclass
class Method_Put:
    pass


@dataclass
class Method_Delete:
    pass


@dataclass
class Method_Connect:
    pass


@dataclass
class Method_Options:
    pass


@dataclass
class Method_Trace:
    pass


@dataclass
class Method_Patch:
    pass


@dataclass
class Method_Other:
    value: str


Method = Union[Method_Get, Method_Head, Method_Post, Method_Put, Method_Delete, Method_Connect, Method_Options, Method_Trace, Method_Patch, Method_Other]
"""
This type corresponds to HTTP standard Methods.
"""



@dataclass
class Scheme_Http:
    pass


@dataclass
class Scheme_Https:
    pass


@dataclass
class Scheme_Other:
    value: str


Scheme = Union[Scheme_Http, Scheme_Https, Scheme_Other]
"""
This type corresponds to HTTP standard Related Schemes.
"""


@dataclass
class DnsErrorPayload:
    """
    Defines the case payload type for `DNS-error` above:
    """
    rcode: Optional[str]
    info_code: Optional[int]

@dataclass
class TlsAlertReceivedPayload:
    """
    Defines the case payload type for `TLS-alert-received` above:
    """
    alert_id: Optional[int]
    alert_message: Optional[str]

@dataclass
class FieldSizePayload:
    """
    Defines the case payload type for `HTTP-response-{header,trailer}-size` above:
    """
    field_name: Optional[str]
    field_size: Optional[int]


@dataclass
class ErrorCode_DnsTimeout:
    pass


@dataclass
class ErrorCode_DnsError:
    value: DnsErrorPayload


@dataclass
class ErrorCode_DestinationNotFound:
    pass


@dataclass
class ErrorCode_DestinationUnavailable:
    pass


@dataclass
class ErrorCode_DestinationIpProhibited:
    pass


@dataclass
class ErrorCode_DestinationIpUnroutable:
    pass


@dataclass
class ErrorCode_ConnectionRefused:
    pass


@dataclass
class ErrorCode_ConnectionTerminated:
    pass


@dataclass
class ErrorCode_ConnectionTimeout:
    pass


@dataclass
class ErrorCode_ConnectionReadTimeout:
    pass


@dataclass
class ErrorCode_ConnectionWriteTimeout:
    pass


@dataclass
class ErrorCode_ConnectionLimitReached:
    pass


@dataclass
class ErrorCode_TlsProtocolError:
    pass


@dataclass
class ErrorCode_TlsCertificateError:
    pass


@dataclass
class ErrorCode_TlsAlertReceived:
    value: TlsAlertReceivedPayload


@dataclass
class ErrorCode_HttpRequestDenied:
    pass


@dataclass
class ErrorCode_HttpRequestLengthRequired:
    pass


@dataclass
class ErrorCode_HttpRequestBodySize:
    value: Optional[int]


@dataclass
class ErrorCode_HttpRequestMethodInvalid:
    pass


@dataclass
class ErrorCode_HttpRequestUriInvalid:
    pass


@dataclass
class ErrorCode_HttpRequestUriTooLong:
    pass


@dataclass
class ErrorCode_HttpRequestHeaderSectionSize:
    value: Optional[int]


@dataclass
class ErrorCode_HttpRequestHeaderSize:
    value: Optional[FieldSizePayload]


@dataclass
class ErrorCode_HttpRequestTrailerSectionSize:
    value: Optional[int]


@dataclass
class ErrorCode_HttpRequestTrailerSize:
    value: FieldSizePayload


@dataclass
class ErrorCode_HttpResponseIncomplete:
    pass


@dataclass
class ErrorCode_HttpResponseHeaderSectionSize:
    value: Optional[int]


@dataclass
class ErrorCode_HttpResponseHeaderSize:
    value: FieldSizePayload


@dataclass
class ErrorCode_HttpResponseBodySize:
    value: Optional[int]


@dataclass
class ErrorCode_HttpResponseTrailerSectionSize:
    value: Optional[int]


@dataclass
class ErrorCode_HttpResponseTrailerSize:
    value: FieldSizePayload


@dataclass
class ErrorCode_HttpResponseTransferCoding:
    value: Optional[str]


@dataclass
class ErrorCode_HttpResponseContentCoding:
    value: Optional[str]


@dataclass
class ErrorCode_HttpResponseTimeout:
    pass


@dataclass
class ErrorCode_HttpUpgradeFailed:
    pass


@dataclass
class ErrorCode_HttpProtocolError:
    pass


@dataclass
class ErrorCode_LoopDetected:
    pass


@dataclass
class ErrorCode_ConfigurationError:
    pass


@dataclass
class ErrorCode_InternalError:
    value: Optional[str]


ErrorCode = Union[ErrorCode_DnsTimeout, ErrorCode_DnsError, ErrorCode_DestinationNotFound, ErrorCode_DestinationUnavailable, ErrorCode_DestinationIpProhibited, ErrorCode_DestinationIpUnroutable, ErrorCode_ConnectionRefused, ErrorCode_ConnectionTerminated, ErrorCode_ConnectionTimeout, ErrorCode_ConnectionReadTimeout, ErrorCode_ConnectionWriteTimeout, ErrorCode_ConnectionLimitReached, ErrorCode_TlsProtocolError, ErrorCode_TlsCertificateError, ErrorCode_TlsAlertReceived, ErrorCode_HttpRequestDenied, ErrorCode_HttpRequestLengthRequired, ErrorCode_HttpRequestBodySize, ErrorCode_HttpRequestMethodInvalid, ErrorCode_HttpRequestUriInvalid, ErrorCode_HttpRequestUriTooLong, ErrorCode_HttpRequestHeaderSectionSize, ErrorCode_HttpRequestHeaderSize, ErrorCode_HttpRequestTrailerSectionSize, ErrorCode_HttpRequestTrailerSize, ErrorCode_HttpResponseIncomplete, ErrorCode_HttpResponseHeaderSectionSize, ErrorCode_HttpResponseHeaderSize, ErrorCode_HttpResponseBodySize, ErrorCode_HttpResponseTrailerSectionSize, ErrorCode_HttpResponseTrailerSize, ErrorCode_HttpResponseTransferCoding, ErrorCode_HttpResponseContentCoding, ErrorCode_HttpResponseTimeout, ErrorCode_HttpUpgradeFailed, ErrorCode_HttpProtocolError, ErrorCode_LoopDetected, ErrorCode_ConfigurationError, ErrorCode_InternalError]
"""
These cases are inspired by the IANA HTTP Proxy Error Types:
  <https://www.iana.org/assignments/http-proxy-status/http-proxy-status.xhtml#table-http-proxy-error-types>
"""



@dataclass
class HeaderError_InvalidSyntax:
    pass


@dataclass
class HeaderError_Forbidden:
    pass


@dataclass
class HeaderError_Immutable:
    pass


@dataclass
class HeaderError_SizeExceeded:
    pass


@dataclass
class HeaderError_Other:
    value: Optional[str]


HeaderError = Union[HeaderError_InvalidSyntax, HeaderError_Forbidden, HeaderError_Immutable, HeaderError_SizeExceeded, HeaderError_Other]
"""
This type enumerates the different kinds of errors that may occur when
setting or appending to a `fields` resource.
"""



@dataclass
class RequestOptionsError_NotSupported:
    pass


@dataclass
class RequestOptionsError_Immutable:
    pass


@dataclass
class RequestOptionsError_Other:
    value: Optional[str]


RequestOptionsError = Union[RequestOptionsError_NotSupported, RequestOptionsError_Immutable, RequestOptionsError_Other]
"""
This type enumerates the different kinds of errors that may occur when
setting fields of a `request-options` resource.
"""


class Fields:
    """
    This following block defines the `fields` resource which corresponds to
    HTTP standard Fields. Fields are a common representation used for both
    Headers and Trailers.
    
    A `fields` may be mutable or immutable. A `fields` created using the
    constructor, `from-list`, or `clone` will be mutable, but a `fields`
    resource given by other means (including, but not limited to,
    `request.headers`) might be be immutable. In an immutable fields, the
    `set`, `append`, and `delete` operations will fail with
    `header-error.immutable`.
    
    A `fields` resource should store `field-name`s and `field-value`s in their
    original casing used to construct or mutate the `fields` resource. The `fields`
    resource should use that original casing when serializing the fields for
    transport or when returning them from a method.
    
    Implementations may impose limits on individual field values and on total
    aggregate field section size. Operations that would exceed these limits
    fail with `header-error.size-exceeded`
    """
    
    def __init__(self) -> None:
        """
        Construct an empty HTTP Fields.
        
        The resulting `fields` is mutable.
        """
        raise NotImplementedError

    @classmethod
    def from_list(cls, entries: List[Tuple[str, bytes]]) -> Self:
        """
        Construct an HTTP Fields.
        
        The resulting `fields` is mutable.
        
        The list represents each name-value pair in the Fields. Names
        which have multiple values are represented by multiple entries in this
        list with the same name.
        
        The tuple is a pair of the field name, represented as a string, and
        Value, represented as a list of bytes. In a valid Fields, all names
        and values are valid UTF-8 strings. However, values are not always
        well-formed, so they are represented as a raw list of bytes.
        
        An error result will be returned if any header or value was
        syntactically invalid, if a header was forbidden, or if the
        entries would exceed an implementation size limit.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_http_types_0_3_0_rc_2026_03_15.HeaderError)`
        """
        raise NotImplementedError
    def get(self, name: str) -> List[bytes]:
        """
        Get all of the values corresponding to a name. If the name is not present
        in this `fields`, an empty list is returned. However, if the name is
        present but empty, this is represented by a list with one or more
        empty field-values present.
        """
        raise NotImplementedError
    def has(self, name: str) -> bool:
        """
        Returns `true` when the name is present in this `fields`. If the name is
        syntactically invalid, `false` is returned.
        """
        raise NotImplementedError
    def set(self, name: str, value: List[bytes]) -> None:
        """
        Set all of the values for a name. Clears any existing values for that
        name, if they have been set.
        
        Fails with `header-error.immutable` if the `fields` are immutable.
        
        Fails with `header-error.size-exceeded` if the name or values would
        exceed an implementation-defined size limit.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_http_types_0_3_0_rc_2026_03_15.HeaderError)`
        """
        raise NotImplementedError
    def delete(self, name: str) -> None:
        """
        Delete all values for a name. Does nothing if no values for the name
        exist.
        
        Fails with `header-error.immutable` if the `fields` are immutable.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_http_types_0_3_0_rc_2026_03_15.HeaderError)`
        """
        raise NotImplementedError
    def get_and_delete(self, name: str) -> List[bytes]:
        """
        Delete all values for a name. Does nothing if no values for the name
        exist.
        
        Returns all values previously corresponding to the name, if any.
        
        Fails with `header-error.immutable` if the `fields` are immutable.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_http_types_0_3_0_rc_2026_03_15.HeaderError)`
        """
        raise NotImplementedError
    def append(self, name: str, value: bytes) -> None:
        """
        Append a value for a name. Does not change or delete any existing
        values for that name.
        
        Fails with `header-error.immutable` if the `fields` are immutable.
        
        Fails with `header-error.size-exceeded` if the value would exceed
        an implementation-defined size limit.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_http_types_0_3_0_rc_2026_03_15.HeaderError)`
        """
        raise NotImplementedError
    def copy_all(self) -> List[Tuple[str, bytes]]:
        """
        Retrieve the full set of names and values in the Fields. Like the
        constructor, the list represents each name-value pair.
        
        The outer list represents each name-value pair in the Fields. Names
        which have multiple values are represented by multiple entries in this
        list with the same name.
        
        The names and values are always returned in the original casing and in
        the order in which they will be serialized for transport.
        """
        raise NotImplementedError
    def clone(self) -> Self:
        """
        Make a deep copy of the Fields. Equivalent in behavior to calling the
        `fields` constructor on the return value of `copy-all`. The resulting
        `fields` is mutable.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class RequestOptions:
    """
    Parameters for making an HTTP Request. Each of these parameters is
    currently an optional timeout applicable to the transport layer of the
    HTTP protocol.
    
    These timeouts are separate from any the user may use to bound an
    asynchronous call.
    """
    
    def __init__(self) -> None:
        """
        Construct a default `request-options` value.
        """
        raise NotImplementedError

    def get_connect_timeout(self) -> Optional[int]:
        """
        The timeout for the initial connect to the HTTP Server.
        """
        raise NotImplementedError
    def set_connect_timeout(self, duration: Optional[int]) -> None:
        """
        Set the timeout for the initial connect to the HTTP Server. An error
        return value indicates that this timeout is not supported or that this
        handle is immutable.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_http_types_0_3_0_rc_2026_03_15.RequestOptionsError)`
        """
        raise NotImplementedError
    def get_first_byte_timeout(self) -> Optional[int]:
        """
        The timeout for receiving the first byte of the Response body.
        """
        raise NotImplementedError
    def set_first_byte_timeout(self, duration: Optional[int]) -> None:
        """
        Set the timeout for receiving the first byte of the Response body. An
        error return value indicates that this timeout is not supported or that
        this handle is immutable.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_http_types_0_3_0_rc_2026_03_15.RequestOptionsError)`
        """
        raise NotImplementedError
    def get_between_bytes_timeout(self) -> Optional[int]:
        """
        The timeout for receiving subsequent chunks of bytes in the Response
        body stream.
        """
        raise NotImplementedError
    def set_between_bytes_timeout(self, duration: Optional[int]) -> None:
        """
        Set the timeout for receiving subsequent chunks of bytes in the Response
        body stream. An error return value indicates that this timeout is not
        supported or that this handle is immutable.
        
        Raises: `componentize_py_types.Err(spin_sdk.wit.imports.wasi_http_types_0_3_0_rc_2026_03_15.RequestOptionsError)`
        """
        raise NotImplementedError
    def clone(self) -> Self:
        """
        Make a deep copy of the `request-options`.
        The resulting `request-options` is mutable.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class Request:
    """
    Represents an HTTP Request.
    """
    
    @classmethod
    def new(cls, headers: Fields, contents: Optional[ByteStreamReader], trailers: FutureReader[Result[Optional[Fields], ErrorCode]], options: Optional[RequestOptions]) -> Tuple[Self, FutureReader[Result[None, ErrorCode]]]:
        """
        Construct a new `request` with a default `method` of `GET`, and
        `none` values for `path-with-query`, `scheme`, and `authority`.
        
        `headers` is the HTTP Headers for the Request.
        
        `contents` is the optional body content stream with `none`
        representing a zero-length content stream.
        Once it is closed, `trailers` future must resolve to a result.
        If `trailers` resolves to an error, underlying connection
        will be closed immediately.
        
        `options` is optional `request-options` resource to be used
        if the request is sent over a network connection.
        
        It is possible to construct, or manipulate with the accessor functions
        below, a `request` with an invalid combination of `scheme`
        and `authority`, or `headers` which are not permitted to be sent.
        It is the obligation of the `handler.handle` implementation
        to reject invalid constructions of `request`.
        
        The returned future resolves to result of transmission of this request.
        """
        raise NotImplementedError
    def get_method(self) -> Method:
        """
        Get the Method for the Request.
        """
        raise NotImplementedError
    def set_method(self, method: Method) -> None:
        """
        Set the Method for the Request. Fails if the string present in a
        `method.other` argument is not a syntactically valid method.
        
        Raises: `componentize_py_types.Err(None)`
        """
        raise NotImplementedError
    def get_path_with_query(self) -> Optional[str]:
        """
        Get the combination of the HTTP Path and Query for the Request.  When
        `none`, this represents an empty Path and empty Query.
        """
        raise NotImplementedError
    def set_path_with_query(self, path_with_query: Optional[str]) -> None:
        """
        Set the combination of the HTTP Path and Query for the Request.  When
        `none`, this represents an empty Path and empty Query. Fails is the
        string given is not a syntactically valid path and query uri component.
        
        Raises: `componentize_py_types.Err(None)`
        """
        raise NotImplementedError
    def get_scheme(self) -> Optional[Scheme]:
        """
        Get the HTTP Related Scheme for the Request. When `none`, the
        implementation may choose an appropriate default scheme.
        """
        raise NotImplementedError
    def set_scheme(self, scheme: Optional[Scheme]) -> None:
        """
        Set the HTTP Related Scheme for the Request. When `none`, the
        implementation may choose an appropriate default scheme. Fails if the
        string given is not a syntactically valid uri scheme.
        
        Raises: `componentize_py_types.Err(None)`
        """
        raise NotImplementedError
    def get_authority(self) -> Optional[str]:
        """
        Get the authority of the Request's target URI. A value of `none` may be used
        with Related Schemes which do not require an authority. The HTTP and
        HTTPS schemes always require an authority.
        """
        raise NotImplementedError
    def set_authority(self, authority: Optional[str]) -> None:
        """
        Set the authority of the Request's target URI. A value of `none` may be used
        with Related Schemes which do not require an authority. The HTTP and
        HTTPS schemes always require an authority. Fails if the string given is
        not a syntactically valid URI authority.
        
        Raises: `componentize_py_types.Err(None)`
        """
        raise NotImplementedError
    def get_options(self) -> Optional[RequestOptions]:
        """
        Get the `request-options` to be associated with this request
        
        The returned `request-options` resource is immutable: `set-*` operations
        will fail if invoked.
        
        This `request-options` resource is a child: it must be dropped before
        the parent `request` is dropped, or its ownership is transferred to
        another component by e.g. `handler.handle`.
        """
        raise NotImplementedError
    def get_headers(self) -> Fields:
        """
        Get the headers associated with the Request.
        
        The returned `headers` resource is immutable: `set`, `append`, and
        `delete` operations will fail with `header-error.immutable`.
        """
        raise NotImplementedError
    @classmethod
    def consume_body(cls, this: Self, res: FutureReader[Result[None, ErrorCode]]) -> Tuple[ByteStreamReader, FutureReader[Result[Optional[Fields], ErrorCode]]]:
        """
        Get body of the Request.
        
        Stream returned by this method represents the contents of the body.
        Once the stream is reported as closed, callers should await the returned
        future to determine whether the body was received successfully.
        The future will only resolve after the stream is reported as closed.
        
        This function takes a `res` future as a parameter, which can be used to
        communicate an error in handling of the request.
        
        Note that function will move the `request`, but references to headers or
        request options acquired from it previously will remain valid.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class Response:
    """
    Represents an HTTP Response.
    """
    
    @classmethod
    def new(cls, headers: Fields, contents: Optional[ByteStreamReader], trailers: FutureReader[Result[Optional[Fields], ErrorCode]]) -> Tuple[Self, FutureReader[Result[None, ErrorCode]]]:
        """
        Construct a new `response`, with a default `status-code` of `200`.
        If a different `status-code` is needed, it must be set via the
        `set-status-code` method.
        
        `headers` is the HTTP Headers for the Response.
        
        `contents` is the optional body content stream with `none`
        representing a zero-length content stream.
        Once it is closed, `trailers` future must resolve to a result.
        If `trailers` resolves to an error, underlying connection
        will be closed immediately.
        
        The returned future resolves to result of transmission of this response.
        """
        raise NotImplementedError
    def get_status_code(self) -> int:
        """
        Get the HTTP Status Code for the Response.
        """
        raise NotImplementedError
    def set_status_code(self, status_code: int) -> None:
        """
        Set the HTTP Status Code for the Response. Fails if the status-code
        given is not a valid http status code.
        
        Raises: `componentize_py_types.Err(None)`
        """
        raise NotImplementedError
    def get_headers(self) -> Fields:
        """
        Get the headers associated with the Response.
        
        The returned `headers` resource is immutable: `set`, `append`, and
        `delete` operations will fail with `header-error.immutable`.
        """
        raise NotImplementedError
    @classmethod
    def consume_body(cls, this: Self, res: FutureReader[Result[None, ErrorCode]]) -> Tuple[ByteStreamReader, FutureReader[Result[Optional[Fields], ErrorCode]]]:
        """
        Get body of the Response.
        
        Stream returned by this method represents the contents of the body.
        Once the stream is reported as closed, callers should await the returned
        future to determine whether the body was received successfully.
        The future will only resolve after the stream is reported as closed.
        
        This function takes a `res` future as a parameter, which can be used to
        communicate an error in handling of the response.
        
        Note that function will move the `response`, but references to headers
        acquired from it previously will remain valid.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



