# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import wasi_cli_types_0_3_0_rc_2026_03_15
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


def read_via_stream() -> Tuple[ByteStreamReader, FutureReader[Result[None, wasi_cli_types_0_3_0_rc_2026_03_15.ErrorCode]]]:
    """
    Return a stream for reading from stdin.
    
    This function returns a stream which provides data read from stdin,
    and a future to signal read results.
    
    If the stream's readable end is dropped the future will resolve to success.
    
    If the stream's writable end is dropped the future will either resolve to
    success if stdin was closed by the writer or to an error-code if reading
    failed for some other reason.
    
    Multiple streams may be active at the same time. The behavior of concurrent
    reads is implementation-specific.
    """
    raise NotImplementedError
