# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import wasi_cli_types_0_3_0_rc_2026_03_15
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


def write_via_stream(data: ByteStreamReader) -> FutureReader[Result[None, wasi_cli_types_0_3_0_rc_2026_03_15.ErrorCode]]:
    """
    Write the given stream to stdout.
    
    If the stream's writable end is dropped this function will either return
    success once the entire contents of the stream have been written or an
    error-code representing a failure.
    
    Otherwise if there is an error the readable end of the stream will be
    dropped and this function will return an error-code.
    """
    raise NotImplementedError
