# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
This interface defines a handler of HTTP Requests.

In a `wasi:http/service` this interface is exported to respond to an
incoming HTTP Request with a Response.

In `wasi:http/middleware` this interface is both exported and imported as
the "downstream" and "upstream" directions of the middleware chain.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter

