""" Module with the bindings generated from the wit by componentize-py """

# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from .imports import spin_key_value_key_value_3_0_0
from .imports import spin_postgres_postgres_4_2_0
from .imports import spin_sqlite_sqlite_3_1_0
from .imports import wasi_filesystem_types_0_3_0_rc_2026_03_15
from .imports import wasi_sockets_types_0_3_0_rc_2026_03_15
from .imports import wasi_cli_types_0_3_0_rc_2026_03_15
from .imports import wasi_http_types_0_3_0_rc_2026_03_15
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter

def byte_stream() -> tuple[ByteStreamWriter, ByteStreamReader]:
    raise NotImplementedError

def result_option_wasi_http_types_0_3_0_rc_2026_03_15_fields_wasi_http_types_0_3_0_rc_2026_03_15_error_code_future(default: Callable[[], Result[Optional[wasi_http_types_0_3_0_rc_2026_03_15.Fields], wasi_http_types_0_3_0_rc_2026_03_15.ErrorCode]]) -> tuple[FutureWriter[Result[Optional[wasi_http_types_0_3_0_rc_2026_03_15.Fields], wasi_http_types_0_3_0_rc_2026_03_15.ErrorCode]], FutureReader[Result[Optional[wasi_http_types_0_3_0_rc_2026_03_15.Fields], wasi_http_types_0_3_0_rc_2026_03_15.ErrorCode]]]:
    raise NotImplementedError

def result_unit_wasi_http_types_0_3_0_rc_2026_03_15_error_code_future(default: Callable[[], Result[None, wasi_http_types_0_3_0_rc_2026_03_15.ErrorCode]]) -> tuple[FutureWriter[Result[None, wasi_http_types_0_3_0_rc_2026_03_15.ErrorCode]], FutureReader[Result[None, wasi_http_types_0_3_0_rc_2026_03_15.ErrorCode]]]:
    raise NotImplementedError

def string_stream() -> tuple[StreamWriter[str], StreamReader[str]]:
    raise NotImplementedError

def result_unit_spin_key_value_key_value_3_0_0_error_future(default: Callable[[], Result[None, spin_key_value_key_value_3_0_0.Error]]) -> tuple[FutureWriter[Result[None, spin_key_value_key_value_3_0_0.Error]], FutureReader[Result[None, spin_key_value_key_value_3_0_0.Error]]]:
    raise NotImplementedError

def list_spin_postgres_postgres_4_2_0_db_value_stream() -> tuple[StreamWriter[List[spin_postgres_postgres_4_2_0.DbValue]], StreamReader[List[spin_postgres_postgres_4_2_0.DbValue]]]:
    raise NotImplementedError

def result_unit_spin_postgres_postgres_4_2_0_error_future(default: Callable[[], Result[None, spin_postgres_postgres_4_2_0.Error]]) -> tuple[FutureWriter[Result[None, spin_postgres_postgres_4_2_0.Error]], FutureReader[Result[None, spin_postgres_postgres_4_2_0.Error]]]:
    raise NotImplementedError

def spin_sqlite_sqlite_3_1_0_row_result_stream() -> tuple[StreamWriter[spin_sqlite_sqlite_3_1_0.RowResult], StreamReader[spin_sqlite_sqlite_3_1_0.RowResult]]:
    raise NotImplementedError

def result_unit_spin_sqlite_sqlite_3_1_0_error_future(default: Callable[[], Result[None, spin_sqlite_sqlite_3_1_0.Error]]) -> tuple[FutureWriter[Result[None, spin_sqlite_sqlite_3_1_0.Error]], FutureReader[Result[None, spin_sqlite_sqlite_3_1_0.Error]]]:
    raise NotImplementedError

def result_unit_wasi_cli_types_0_3_0_rc_2026_03_15_error_code_future(default: Callable[[], Result[None, wasi_cli_types_0_3_0_rc_2026_03_15.ErrorCode]]) -> tuple[FutureWriter[Result[None, wasi_cli_types_0_3_0_rc_2026_03_15.ErrorCode]], FutureReader[Result[None, wasi_cli_types_0_3_0_rc_2026_03_15.ErrorCode]]]:
    raise NotImplementedError

def result_unit_wasi_filesystem_types_0_3_0_rc_2026_03_15_error_code_future(default: Callable[[], Result[None, wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode]]) -> tuple[FutureWriter[Result[None, wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode]], FutureReader[Result[None, wasi_filesystem_types_0_3_0_rc_2026_03_15.ErrorCode]]]:
    raise NotImplementedError

def wasi_filesystem_types_0_3_0_rc_2026_03_15_directory_entry_stream() -> tuple[StreamWriter[wasi_filesystem_types_0_3_0_rc_2026_03_15.DirectoryEntry], StreamReader[wasi_filesystem_types_0_3_0_rc_2026_03_15.DirectoryEntry]]:
    raise NotImplementedError

def wasi_sockets_types_0_3_0_rc_2026_03_15_tcp_socket_stream() -> tuple[StreamWriter[Any], StreamReader[Any]]:
    raise NotImplementedError

def result_unit_wasi_sockets_types_0_3_0_rc_2026_03_15_error_code_future(default: Callable[[], Result[None, wasi_sockets_types_0_3_0_rc_2026_03_15.ErrorCode]]) -> tuple[FutureWriter[Result[None, wasi_sockets_types_0_3_0_rc_2026_03_15.ErrorCode]], FutureReader[Result[None, wasi_sockets_types_0_3_0_rc_2026_03_15.ErrorCode]]]:
    raise NotImplementedError


class SpinSdkWit(Protocol):
    pass
